title: GameDevSig
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://gamedevsig.github.io"

# Build settings
future: true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# Default excludes:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - Makefile
  - README.md

collections:
  events:
    output: true

permalink: /:basename/

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
    values:
      layout: "default"

# Default github pages options:
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
